version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"

  postgresql:
    image: postgres:15-bullseye
    container_name: teamwork_postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"